name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which tag do you want to release against?"
        type: string
        required: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos
            arch: aarch64
          - os: ubuntu-24.04-arm
            platform: linux
            arch: aarch64
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Predoc
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.version }}
          path: predoc
      - name: Check out Wattle
        uses: actions/checkout@v7
        with:
          repository: pyrmont/wattle
          path: wattle
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build Wattle
        run: zig build
        working-directory: wattle
      - name: Run Wattle tests
        run: ../wattle/zig-out/bin/wattle test
        working-directory: predoc
      - name: Build Predoc
        run: ../wattle/zig-out/bin/wattle -p ../wattle/zig-out build exe --release fast
        working-directory: predoc
      - name: Package Predoc
        run: |
          package="predoc-${{ inputs.version }}"
          mkdir "$package"
          cp zig-out/bin/predoc man/man1/predoc.1 man/man7/predoc.7 LICENSE "$package/"
          tar -czf "${package}-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz" "$package"
        working-directory: predoc
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.platform }}-${{ matrix.arch }}
          path: predoc/predoc-${{ inputs.version }}-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: "download artifacts"
      uses: actions/download-artifact@v8
      with:
        path: ./artifacts
        merge-multiple: true
    - name: "draft the release"
      uses: softprops/action-gh-release@v3
      with:
        draft: true
        files: ./artifacts/*
        overwrite_files: false
        tag_name: ${{ inputs.version }}
