name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Predoc
        uses: actions/checkout@v7
        with:
          path: predoc
      - name: Check out Wattle
        uses: actions/checkout@v7
        with:
          repository: pyrmont/wattle
          path: wattle
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build Wattle
        run: zig build
        working-directory: wattle
      - name: Build Predoc
        run: ../wattle/zig-out/bin/wattle -p ../wattle/zig-out build exe
        working-directory: predoc
      - name: Run Wattle tests
        run: ../wattle/zig-out/bin/wattle test
        working-directory: predoc
      - name: Check CLI
        run: |
          zig-out/bin/predoc --help
          zig-out/bin/predoc --no-ad --output - man/man1/predoc.1.predoc
        working-directory: predoc
